### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by kouts** [yisibell/vite-plugin-svg4vue#1]
Thanks for this great plugin.
I'm using it with VITE v4.3.2 and I get the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /{PATH_TO_PROJECT}/node_modules/vite-plugin-svg4vue/lib/index.cjs.js from /{PATH_TO_PROJECT}/vite.config.ts not supported.
```
This must be related to https://github.com/vitejs/vite/issues/6623, so renaming `vite.config.ts` to `vite.config.mts` solved it. 
I saw that there's a `.cjs` version of the plugin, is there anyway to use that so that I don't have to rename vite config? I'm not sure what the possible implications are when renaming the config.

**Comment by yisibell** [comment]
just change the `type` to `module` in `package.json` of your project.
