### ISSUE TITLE
Doesn't work with ?component query string

### ISSUE THREAD

**Issue by kouts** [yisibell/vite-plugin-svg4vue#2]
Using VITE v4.3.2 I get an error when I try to import an SVG as a Vue component.

`[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core `

Sample code:
```
<script>
import LogoSvg from '@/assets/logo.svg?component';

export default {
  components: {
    LogoSvg,
  }
}
</script>

<template>
  <div>
    <LogoSvg />
  </div>
</template>
```

**Comment by yisibell** [comment]
Place your SVG in the folder defined by `assetsDirName`, and u can configure via:
```ts
// vite.config.ts

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { svg4VuePlugin } from 'vite-plugin-svg4vue'

export default defineConfig({
  plugins: [
    vue(),
    svg4VuePlugin({
      assetsDirName: 'assets/icons'
   }),
  ],
})
```

**Comment by kouts** [comment]
Thank you @yisibell that solved it.
Is there any way to make it work with arbitrary file path?

**Comment by yisibell** [comment]
Not having folder restrictions is not a good idea as it conflicts with vite's default SVG loader.

**Comment by yisibell** [comment]
> Thank you @yisibell that solved it. Is there any way to make it work with arbitrary file path?

```ts
// vite.config.ts

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { svg4VuePlugin } from 'vite-plugin-svg4vue'

export default defineConfig({
  plugins: [
    vue(),
    svg4VuePlugin({
      assetsDirName: 'icons' // this is default value
   }),
  ],
})
```

By the way, if you set `assetsDirName` to `icons`:  you can also place your svg icon  in these folders that `path/to/icons`,`path/icons`, `icons` and so on.

Just place your SVG icon under the `icons` file, no matter how deep the folder is nested.

**Comment by yisibell** [comment]
> Thank you @yisibell that solved it. Is there any way to make it work with arbitrary file path?

Now, In vite-plugin-svg4vue **2.12.0**, just set `assetsDirName` to `false`, will make it work with arbitrary file path.
