### ISSUE TITLE
vite已更新到5.0

### ISSUE THREAD

**Issue by Mophar-gift** [yisibell/vite-plugin-svg4vue#4]
## 目前Vite已更新到5.0版本
![image](https://github.com/yisibell/vite-plugin-svg4vue/assets/67857649/28cc4645-3c31-4a48-9d9f-9e98cda383f3)

## 使用最新版本vite安装会出现警告，请及时更新适配哦

**Comment by yisibell** [comment]
> ## 目前Vite已更新到5.0版本
> ![image](https://user-images.githubusercontent.com/67857649/283641768-28cc4645-3c31-4a48-9d9f-9e98cda383f3.png)
> 
> ## 使用最新版本vite安装会出现警告，请及时更新适配哦

Already supported in `v3` and also `v2.17.3`
