### ISSUE TITLE
打包时出现错误

### ISSUE THREAD

**Issue by Mophar-gift** [yisibell/vite-plugin-svg4vue#5]
![image](https://github.com/yisibell/vite-plugin-svg4vue/assets/67857649/a5120fd9-44b6-497e-be9f-01ca06da4ad0)

## 本地开发时没发现问题，只有build时会出现

**Comment by yisibell** [comment]
请提供下出错时的 SVG 导入源码截图。

**Comment by Mophar-gift** [comment]
![image](https://github.com/yisibell/vite-plugin-svg4vue/assets/67857649/90b00902-ffaf-4bc6-8e6d-9c38ede1b921)

[zaSvgIcon.zip](https://github.com/yisibell/vite-plugin-svg4vue/files/13724360/zaSvgIcon.zip)

**Comment by Mophar-gift** [comment]
之前用的 2.17.1 版本，当时并没有这个错误

**Comment by yisibell** [comment]
如果这里的 `@/assets/svg/*.svg` 图标需要被 `vite-plugin-svg4vue` 处理的话。写法需要修改如下：
```ts
const modules = import.meta.glob('@/assets/svg/*.svg', {
    eager: true,
    query: {
        component: '' //  告诉插件将 svg 处理为 vue 组件。
        // raw: ''  // 或者将 svg 处理为纯文本
    }
})
```

**Comment by Mophar-gift** [comment]
> 如果这里的 `@/assets/svg/*.svg` 图标需要被 `vite-plugin-svg4vue` 处理的话。写法需要修改如下：
> 
> ```ts
> const modules = import.meta.glob('@/assets/svg/*.svg', {
>     eager: true,
>     query: {
>         component: '' //  告诉插件将 svg 处理为 vue 组件。
>         // raw: ''  // 或者将 svg 处理为纯文本
>     }
> })
> ```

![image](https://github.com/yisibell/vite-plugin-svg4vue/assets/67857649/3fe4d378-85f0-4962-bfd7-5d774fb84760)
这个写法没太明白，我是直接这样写吗，component的值为什么

**Comment by Mophar-gift** [comment]
> > 如果这里的 `@/assets/svg/*.svg` 图标需要被 `vite-plugin-svg4vue` 处理的话。写法需要修改如下：
> > ```ts
> > const modules = import.meta.glob('@/assets/svg/*.svg', {
> >     eager: true,
> >     query: {
> >         component: '' //  告诉插件将 svg 处理为 vue 组件。
> >         // raw: ''  // 或者将 svg 处理为纯文本
> >     }
> > })
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/67857649/291832304-3fe4d378-85f0-4962-bfd7-5d774fb84760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE4NjEsIm5iZiI6MTcwMzA2MTU2MSwicGF0aCI6Ii82Nzg1NzY0OS8yOTE4MzIzMDQtM2ZlNGQzNzgtODVmMC00OTYyLWJmZDctNWQ3NzRmYjg0NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4MzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzMxNWQxNGVhZjI0OTEyMWZmZGM1MjBiZDE2MzQxYWYyYjNkZDcwMzc1MmI5YjU4OGZhNmQ3ZTk2NGJkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iE5D9j0tV7r4Opb2H6dcD0ara0iEWrqeO25Ei6Qw8k) 这个写法没太明白，我是直接这样写吗，component的值为什么

![image](https://github.com/yisibell/vite-plugin-svg4vue/assets/67857649/d6f6003c-4453-406e-bff3-11d26de588fa)
直接这样写，还是一样报错，这里的component或者raw的值应该为什么，可以举个例子吗，还是直接为空

**Comment by yisibell** [comment]
> > > 如果这里的 `@/assets/svg/*.svg` 图标需要被 `vite-plugin-svg4vue` 处理的话。写法需要修改如下：
> > > ```ts
> > > const modules = import.meta.glob('@/assets/svg/*.svg', {
> > >     eager: true,
> > >     query: {
> > >         component: '' //  告诉插件将 svg 处理为 vue 组件。
> > >         // raw: ''  // 或者将 svg 处理为纯文本
> > >     }
> > > })
> > > ```
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/67857649/291832304-3fe4d378-85f0-4962-bfd7-5d774fb84760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE4NjEsIm5iZiI6MTcwMzA2MTU2MSwicGF0aCI6Ii82Nzg1NzY0OS8yOTE4MzIzMDQtM2ZlNGQzNzgtODVmMC00OTYyLWJmZDctNWQ3NzRmYjg0NzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4MzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzMxNWQxNGVhZjI0OTEyMWZmZGM1MjBiZDE2MzQxYWYyYjNkZDcwMzc1MmI5YjU4OGZhNmQ3ZTk2NGJkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iE5D9j0tV7r4Opb2H6dcD0ara0iEWrqeO25Ei6Qw8k) 这个写法没太明白，我是直接这样写吗，component的值为什么
> 
> ![image](https://private-user-images.githubusercontent.com/67857649/291832798-d6f6003c-4453-406e-bff3-11d26de588fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjE5NjksIm5iZiI6MTcwMzA2MTY2OSwicGF0aCI6Ii82Nzg1NzY0OS8yOTE4MzI3OTgtZDZmNjAwM2MtNDQ1My00MDZlLWJmZjMtMTFkMjZkZTU4OGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NmZjZDVkN2UxNmZkNDc5ZWI3YjEwZWM3YjI3MWY0NTZhOGRjMTUwMjg0NzUyNmY4YTQ5NDFmMjM5MmY2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrKppRoNQJQxfZ1_FPiv3rjlZq-_5u16b4oofiU9nAU) 直接这样写，还是一样报错，这里的component或者raw的值应该为什么，可以举个例子吗，还是直接为空

空字符串就行，另外把 `vite-plugin-svg4vue` 升级至 `v3.1.0`

**Comment by Mophar-gift** [comment]
好的，升级后可以了👌，感谢答疑
